### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by adhocore**
**Changes**

Update readme- use syntax highlight and fix typo
Travis- retire PHP pre v5.6, add 7.1, 7.2, 7.3
Fix coding standards
Provide options for phpunit versions according as platform
Add backslash to global functions for performance
Fix the PHPUnit class namespace

*PS*, donot fear the large diff there is nothing sneaky ;)

### CODE REVIEW

**Comment by Fale** [comment]
Thanks a lot!

**Comment by adhocore** [comment]
How about v3.1.0 release? :)

**Comment by Fale** [comment]
v3.1.0 released ;-)

**Comment by adhocore** [comment]
Cool

**Pull request merged**
